apiVersion: v1
kind: Secret
metadata:
  name: my-nexus-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsb2NhbGhvc3Q6MzM5MzQiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4ifX19




