apiVersion: apps/v1
kind: Deployment
metadata:
  name: house
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house
  template:
    metadata:
      labels:
        app: house
    spec:
      imagePullSecrets:
        - name: my-nexus-creds
      containers:
        - name: app
          image: localhost:48678/house:0.0.20
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: test
            - name: MONGODB_COLLECTION
              value: test
              value: watchtower
              value: SpringBoot_KeyCloak
---
apiVersion: v1
kind: Service
metadata:
  name: house
spec:
  selector:
    app: house
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
