pipeline {
    agent any
    tools {
        maven "maven-version"
    }
    environment {
        DOCKER_REGISTRY = 'localhost:31551'
        DOCKER_IMAGE_NAME = 'house'
        DOCKER_IMAGE_TAG = "0.0." + "${env.BUILD_NUMBER}"
        NEXUS_REPOSITORY = 'localhost:31551'
    }
    
    stages  {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/hasretagaslan/jenkins-project.git'
            }
        }
        stage('Create Jar Files') {
            steps {
                sh 'cd ./RestApi && mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('Sonarqube-10.0') { // You can override the credential to be used
                    sh '''
                        cd ./RestApi && mvn clean verify sonar:sonar \
                        -Dsonar.projectKey=maven-jenkins-pipeline \
                        -Dsonar.projectName='maven-jenkins-pipeline' \
                        -Dsonar.host.url=http://192.168.1.10:9000 \
                        -Dsonar.token=sqp_bacb57c2890f57297eeac3d8efd32f4daac06fde
                    '''
                }
           } 
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} -f ./RestApi/DockerFile ."
            }
        }
        stage('Push Docker Image to Nexus Repository') {
            steps {
                sh "docker login ${DOCKER_REGISTRY} -u admin-p admin"
                sh "docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${NEXUS_REPOSITORY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                sh "docker push ${NEXUS_REPOSITORY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
            }
        }
        stage('Change House Version') {
            steps {
                sh "sed -i _E 's('house':.+)/'house':'[${DOCKER_IMAGE_TAG}]' '/' kubernetes/house.yaml"
                
            }
            
        }
        stage('Deploy new Version') {
            steps {
                sh "kubectl apply -f kubernetes/house.yaml"
            }
        }
    
    }

 }