apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sonarqube
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/sonarqube
